sudo: required
services:
  - docker

before_install:
  - docker build -t aleksijaakkojuhani/docker-nextjs -f Dockerfile.dev .

script:
  - docker run aleksijaakkojuhani/docker-nextjs npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-893692417624"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"