version: '3'
services:
  nextjs:
    build: .
      #context: .
      #dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  nginx:
    build: ./nginx
    ports:
      - 80:80
  tests:
    build: .
      #context: .
      #dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]